[tool.poetry]
name = "tree-view"
version = "0.1.0"
description = ""
authors = ["Heiko <git@heiko-braun.org>"]
readme = "README.md"
packages = [{include = "tree_view"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
